services:
  - type: web
    name: llm-backend
    env: python
    buildCommand: pip install -r requirements.txt.txt.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY
